name: Build LaTeX document
on:
    push:
        tags:
            - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: card.tex
          latexmk_use_xelatex: true
      - name: Add and commit PDF file
        run: |
          git config --global user.name "pdf_uploader[bot]"
          git config --global user.email "donot-mail@users.noreply.github.com"
          git add card.pdf
          git commit -m "[AUTOMATIC] Added new card.pdf"
          git push origin HEAD:2-no-release-created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
            title: "New release"
      - name: Remove card.pdf from tracked files
        run: |
            git rm -r --cached card.pdf
            git commit -m "[AUTOMATIC] Untrack card.pdf"
            git push origin HEAD:2-no-release-created
